IDX Exchange DS47 Code: Joe Hiller
Initial step: Create train-test split. For first split: read in six months of data from 06-2025 to 11-2025. Use 12-2025 as test set. For second split: read in six months of data from 07-2025 to 12-2025. Use 1-2026 as test set.



For both train and test, ensure that property type is residential and propertySubType is single family residence. 

According to Wikipedia, the latitude and longitude ranges for California are:
Latitude	32°32′ N to 42° N
Longitude	114°8′ W to 124°26′ W
Angle units are defined in decimal parts by dividing by 60. e.g. 32' = 32/60.

In [1]:
import pandas as pd
from sklearn.metrics import mean_absolute_percentage_error as mape
import numpy as np

LAT_MIN = 32.0 + 32.0/60
LAT_MAX = 42.0
LON_MIN = -124.0 + 26.0/60
LON_MAX = -114.0 + 8.0/60


# reads csv files into dataframes
df0 = pd.read_csv("CRMLSSold202506.csv")
df1 = pd.read_csv("CRMLSSold202507.csv")
df2 = pd.read_csv("CRMLSSold202508.csv")
df3 = pd.read_csv("CRMLSSold202509.csv")
df4 = pd.read_csv("CRMLSSold202510.csv")
df5 = pd.read_csv("CRMLSSold202511.csv")
df6 = pd.read_csv("CRMLSSold202512.csv")
df7 = pd.read_csv("CRMLSSold202601.csv")
# Creates train test split ending in december
df_train_dec = pd.concat([df0, df1, df2, df3, df4, df5], axis = 0)
df_test_dec = df6
# Filters the data
df_train_dec = df_train_dec[(df_train_dec["PropertyType"] == "Residential") & (df_train_dec["PropertySubType"] == "SingleFamilyResidence")]
df_test_dec = df_test_dec[(df_test_dec["PropertyType"] == "Residential") & (df_test_dec["PropertySubType"] == "SingleFamilyResidence")]

# filters out invalid data
df_train_dec = df_train_dec[(df_train_dec["ClosePrice"] > 0) & (df_train_dec["LivingArea"] > 0)]
df_train_dec = df_train_dec[df_train_dec["StateOrProvince"] == "CA"] 


# filters out invalid test data
df_test_dec = df_test_dec[(df_test_dec["ClosePrice"] > 0) & (df_test_dec["LivingArea"] > 0)]
df_test_dec = df_test_dec[df_test_dec["StateOrProvince"] == "CA"]
# df_test_dec = df_test_dec.dropna(subset = ["Latitude", "Longitude"])

#filter to only properties in california

df_train_dec.loc[
    ~df_train_dec["Latitude"].between(LAT_MIN, LAT_MAX),
    "Latitude"
] = None

df_train_dec.loc[~df_train_dec["Longitude"].between(LON_MIN, LON_MAX), "Longitude"] = None


df_train_dec = df_train_dec.dropna(subset = ["Latitude", "Longitude"])

df_test_dec.loc[
    ~df_test_dec["Latitude"].between(LAT_MIN, LAT_MAX), 
    "Latitude"
] = None

df_test_dec.loc[
    ~df_test_dec["Longitude"].between(LON_MIN, LON_MAX),
    "Longitude"
] = None

df_test_dec = df_test_dec.dropna(subset = ["Latitude", "Longitude"])

#removes duplicates from train and test data

df_train_dec['CloseDate'] = pd.to_datetime(df_train_dec['CloseDate'])

df_train_dec = (
    df_train_dec.sort_values('CloseDate', ascending=False)
      .drop_duplicates(subset='ListingKey', keep='first')
)

df_test_dec['CloseDate'] = pd.to_datetime(df_test_dec['CloseDate'])
df_test_dec = (
    df_test_dec.sort_values('CloseDate', ascending=False)
      .drop_duplicates(subset="ListingKey", keep='first')
)

C:\Users\jehil\AppData\Local\Temp\ipykernel_17756\1688373431.py:12: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df0 = pd.read_csv("CRMLSSold202506.csv")
C:\Users\jehil\AppData\Local\Temp\ipykernel_17756\1688373431.py:19: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df7 = pd.read_csv("CRMLSSold202601.csv")

I created the train and test sets for the data period ending in January 2026. I applied the same data preprocessing techniques to this train and test set for consistency.

In [2]:
df_train_jan = pd.concat([df1, df2, df3, df4, df5, df6], axis = 0)
df_test_jan = df7

df_train_jan = df_train_jan[(df_train_jan["PropertyType"] == "Residential") & (df_train_jan["PropertySubType"] == "SingleFamilyResidence")]
df_test_jan = df_test_jan[(df_test_jan["PropertyType"] == "Residential") & (df_test_jan["PropertySubType"] == "SingleFamilyResidence")]

# filters out invalid data
df_train_jan = df_train_jan[(df_train_jan["ClosePrice"] > 0) & (df_train_jan["LivingArea"] > 0)]
df_train_jan = df_train_jan[df_train_jan["StateOrProvince"] == "CA"] 


# filters out invalid test data
df_test_jan = df_test_jan[(df_test_jan["ClosePrice"] > 0) & (df_test_jan["LivingArea"] > 0)]
df_test_jan = df_test_jan[df_test_jan["StateOrProvince"] == "CA"]


#filter to only properties in california

df_train_jan.loc[
    ~df_train_jan["Latitude"].between(LAT_MIN, LAT_MAX),
    "Latitude"
] = None

df_train_jan.loc[~df_train_jan["Longitude"].between(LON_MIN, LON_MAX), "Longitude"] = None


df_train_jan = df_train_jan.dropna(subset = ["Latitude", "Longitude"])

df_test_jan.loc[
    ~df_test_jan["Latitude"].between(LAT_MIN, LAT_MAX), 
    "Latitude"
] = None

df_test_jan.loc[
    ~df_test_jan["Longitude"].between(LON_MIN, LON_MAX),
    "Longitude"
] = None

df_test_jan = df_test_jan.dropna(subset = ["Latitude", "Longitude"])

df_train_jan['CloseDate'] = pd.to_datetime(df_train_jan['CloseDate'])

df_train_jan = (
    df_train_jan.sort_values('CloseDate', ascending=False)
      .drop_duplicates(subset='ListingKey', keep='first')
)

df_test_jan['CloseDate'] = pd.to_datetime(df_test_jan["CloseDate"])

df_test_jan = (
    df_test_jan.sort_values('CloseDate', ascending=False)
      .drop_duplicates(subset='ListingKey', keep='first')
)

I know calculate the missing percentage for each variable. If the missing percentage is above 15% I don't include it in the model, as 15% of the data should not be imputed.

In [3]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)


missing_dec = (df_train_dec.isna().sum() / len(df_train_dec)) * 100
missing_pcts = missing_dec.sort_values(ascending = False)
print(missing_pcts)
pd.reset_option("display.max_columns")
pd.reset_option("display.max_rows")

MiddleOrJuniorSchoolDistrict    100.000000
FireplacesTotal                 100.000000
AboveGradeFinishedArea          100.000000
TaxAnnualAmount                 100.000000
TaxYear                         100.000000
ElementarySchoolDistrict        100.000000
CoveredSpaces                   100.000000
BusinessType                    100.000000
WaterfrontYN                     99.960460
BelowGradeFinishedArea           99.283894
BasementYN                       97.541224
BuilderName                      95.426588
LotSizeDimensions                93.582872
BuildingAreaTotal                93.298773
CoBuyerAgentFirstName            90.673052
ElementarySchool                 86.831854
MiddleOrJuniorSchool             86.612190
HighSchool                       82.675805
CoListAgentFirstName             76.446124
CoListAgentLastName              76.374367
AssociationFeeFrequency          75.047594
CoListOfficeName                 73.354714
SubdivisionName                  64.541780
MainLevelBedrooms                39.062180
Flooring                         34.868055
AssociationFee                   29.407199
HighSchoolDistrict               26.794658
MLSAreaMajor                     15.066046
AttachedGarageYN                 11.954134
Stories                          10.252468
ViewYN                            9.527575
PoolPrivateYN                     7.714612
NewConstructionYN                 7.543274
Levels                            6.900390
BuyerOfficeAOR                    5.966084
GarageSpaces                      4.019858
LotSizeSquareFeet                 1.688487
LotSizeAcres                      1.685558
LotSizeArea                       1.673842
BuyerOfficeName                   1.146648
ListAgentFirstName                0.717570
BuyerAgentFirstName               0.434935
ListAgentEmail                    0.341212
OriginalListPrice                 0.206484
BuyerAgentMlsId                   0.103974
StreetNumberNumeric               0.090795
UnparsedAddress                   0.070293
FireplaceYN                       0.068828
YearBuilt                         0.051255
BuyerAgentLastName                0.041004
City                              0.033682
ListAgentFullName                 0.027824
BuyerAgentAOR                     0.016109
BathroomsTotalInteger             0.016109
ListAgentAOR                      0.016109
ListAgentLastName                 0.011715
PurchaseContractDate              0.007322
PostalCode                        0.001464
ParkingTotal                      0.001464
PropertyType                      0.000000
ListPrice                         0.000000
ListingKeyNumeric                 0.000000
ListOfficeName                    0.000000
CountyOrParish                    0.000000
MlsStatus                         0.000000
DaysOnMarket                      0.000000
ListingKey                        0.000000
LivingArea                        0.000000
PropertySubType                   0.000000
ContractStatusChangeDate          0.000000
ListingId                         0.000000
CloseDate                         0.000000
ClosePrice                        0.000000
StateOrProvince                   0.000000
ListingContractDate               0.000000
Latitude                          0.000000
Longitude                         0.000000
BedroomsTotal                     0.000000
dtype: float64

In [4]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)


missing_jan = (df_train_jan.isna().sum() / len(df_train_jan)) * 100
missing_jan_percents = missing_jan.sort_values(ascending = False)
print(missing_jan_percents)
pd.reset_option("display.max_columns")
pd.reset_option("display.max_rows")

MiddleOrJuniorSchoolDistrict    100.000000
FireplacesTotal                 100.000000
AboveGradeFinishedArea          100.000000
TaxAnnualAmount                 100.000000
TaxYear                         100.000000
ElementarySchoolDistrict        100.000000
CoveredSpaces                   100.000000
BusinessType                    100.000000
WaterfrontYN                     99.959718
BelowGradeFinishedArea           99.271935
BasementYN                       97.617378
BuilderName                      95.537619
LotSizeDimensions                93.590643
BuildingAreaTotal                93.290763
CoBuyerAgentFirstName            90.802214
ElementarySchool                 87.041043
MiddleOrJuniorSchool             86.882898
HighSchool                       82.914348
CoListAgentFirstName             76.588539
CoListAgentLastName              76.521402
AssociationFeeFrequency          75.092127
CoListOfficeName                 73.446522
SubdivisionName                  64.808212
MainLevelBedrooms                38.491951
Flooring                         35.332030
AssociationFee                   28.904770
HighSchoolDistrict               26.575857
MLSAreaMajor                     14.841780
AttachedGarageYN                 12.145852
Stories                           9.979560
ViewYN                            9.312665
PoolPrivateYN                     7.544721
NewConstructionYN                 7.502947
BuyerOfficeAOR                    6.904680
Levels                            6.619720
GarageSpaces                      3.984961
LotSizeSquareFeet                 1.660525
LotSizeAcres                      1.659033
LotSizeArea                       1.650081
BuyerOfficeName                   1.095081
ListAgentFirstName                0.701210
BuyerAgentFirstName               0.411774
ListAgentEmail                    0.347621
OriginalListPrice                 0.195444
BuyerAgentMlsId                   0.122339
StreetNumberNumeric               0.098468
UnparsedAddress                   0.071613
FireplaceYN                       0.071613
BuyerAgentLastName                0.050726
YearBuilt                         0.047742
ListAgentFullName                 0.034315
City                              0.019395
BuyerAgentAOR                     0.016411
ListAgentAOR                      0.016411
ListAgentLastName                 0.010444
BathroomsTotalInteger             0.010444
PurchaseContractDate              0.007460
PostalCode                        0.001492
PropertyType                      0.000000
ListPrice                         0.000000
ListingKeyNumeric                 0.000000
ListOfficeName                    0.000000
CountyOrParish                    0.000000
MlsStatus                         0.000000
DaysOnMarket                      0.000000
ParkingTotal                      0.000000
ListingKey                        0.000000
LivingArea                        0.000000
PropertySubType                   0.000000
ContractStatusChangeDate          0.000000
ListingId                         0.000000
CloseDate                         0.000000
ClosePrice                        0.000000
StateOrProvince                   0.000000
ListingContractDate               0.000000
Latitude                          0.000000
Longitude                         0.000000
BedroomsTotal                     0.000000
dtype: float64

I found the intersection of features where both December and January endings appear. I removed ListPrice, OriginalListPrice, PurchaseContractDate, and CloseDate as it has to do with the time of sale.

In [5]:

cols = ["ClosePrice", "AttachedGarageYN", "Stories", "ViewYN", "PoolPrivateYN", "NewConstructionYN", "Levels", "BuyerOfficeAOR", "GarageSpaces", "LotSizeSquareFeet", "LotSizeAcres", "LotSizeArea", "BuyerOfficeName", "ListAgentFirstName", "BuyerAgentFirstName", "ListAgentEmail", "BuyerAgentMlsId", "StreetNumberNumeric", "UnparsedAddress", "FireplaceYN", "YearBuilt", "BuyerAgentLastName", "City", "ListAgentFullName", "BuyerAgentAOR", "BathroomsTotalInteger", "ListAgentAOR", "ListAgentLastName", "PostalCode", "ParkingTotal", "PropertyType", "ListingKeyNumeric", "ListOfficeName", "CountyOrParish", "MlsStatus", "DaysOnMarket", "ListingKey", "LivingArea", "PropertySubType", "ContractStatusChangeDate", "ListingId", "StateOrProvince", "ListingContractDate", "Latitude", "Longitude", "BedroomsTotal"]                            

df_train_dec = df_train_dec[cols]

df_test_dec = df_test_dec[cols]
c_price = "ClosePrice"
test_low = df_test_dec[c_price].quantile(0.005)
test_high = df_test_dec[c_price].quantile(0.995)
df_test_dec = df_test_dec[(df_test_dec[c_price] >= test_low) & (df_test_dec[c_price] <= test_high)]
df_test_dec

,ClosePrice,AttachedGarageYN,Stories,ViewYN,PoolPrivateYN,NewConstructionYN,Levels,BuyerOfficeAOR,GarageSpaces,LotSizeSquareFeet,...,ListingKey,LivingArea,PropertySubType,ContractStatusChangeDate,ListingId,StateOrProvince,ListingContractDate,Latitude,Longitude,BedroomsTotal
0,1998000.0,True,1.0,NaN,False,False,One,ContraCosta,3.0,10080.0,...,1150041639,2045.0,SingleFamilyResidence,2025-12-31,41119782,CA,2025-12-31,37.871927,-122.029871,4.0
4072,1189000.0,True,1.0,True,False,False,One,OrangeCounty,2.0,4888.0,...,1146066190,1900.0,SingleFamilyResidence,2025-12-31,OC25254021,CA,2025-11-04,33.649317,-117.629635,2.0
13836,455000.0,True,1.0,NaN,True,False,One,CitrusValley,2.0,6534.0,...,1135662476,1687.0,SingleFamilyResidence,2025-12-31,IV25218752,CA,2025-09-17,33.957642,-116.999962,2.0
1437,5275000.0,NaN,2.0,False,False,False,Two,NaN,NaN,5301.0,...,1147260067,2880.0,SingleFamilyResidence,2025-12-31,25623811,CA,2025-12-01,33.992829,-118.461618,3.0
13686,900000.0,True,2.0,True,False,False,Two,PacificWest,2.0,7841.0,...,1135751174,2575.0,SingleFamilyResidence,2025-12-31,IG25220572,CA,2025-09-18,33.871405,-117.604177,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14307,915000.0,False,1.0,False,False,False,One,PacificWest,2.0,5882.0,...,1133924879,1318.0,SingleFamilyResidence,2025-12-01,IG25216123,CA,2025-09-12,33.975442,-118.032678,3.0
14348,740894.0,NaN,2.0,False,False,False,Two,Mrmls,2.0,0.0,...,1133869432,1691.0,SingleFamilyResidence,2025-12-01,SDC0001204SD,CA,2025-09-06,33.345481,-117.150766,3.0
14373,640000.0,False,1.0,False,False,False,One,Glendale,NaN,6326.0,...,1133803889,1188.0,SingleFamilyResidence,2025-12-01,GD25215487,CA,2025-09-12,33.927084,-118.331328,3.0
14375,1300000.0,False,1.0,True,False,False,One,SouthBay,2.0,7005.0,...,1133802220,1341.0,SingleFamilyResidence,2025-12-01,SB25197276,CA,2025-05-26,33.963929,-118.419502,3.0
20536,842000.0,True,1.0,True,False,False,One,OrangeCounty,2.0,7275.0,...,425795803,1642.0,SingleFamilyResidence,2025-12-01,IG20153137,CA,2020-08-09,33.746161,-118.022037,3.0

I applied the same columns to the data ending in January and found the range of prices in that area

In [6]:



df_train_jan = df_train_jan[cols]

df_test_jan = df_test_jan[cols]
c_price = "ClosePrice"
test_low = df_test_jan[c_price].quantile(0.005)
test_high = df_test_jan[c_price].quantile(0.995)
df_test_jan = df_test_jan[(df_test_jan[c_price] >= test_low) & (df_test_jan[c_price] <= test_high)]
df_test_jan

,ClosePrice,AttachedGarageYN,Stories,ViewYN,PoolPrivateYN,NewConstructionYN,Levels,BuyerOfficeAOR,GarageSpaces,LotSizeSquareFeet,...,ListingKey,LivingArea,PropertySubType,ContractStatusChangeDate,ListingId,StateOrProvince,ListingContractDate,Latitude,Longitude,BedroomsTotal
13087,432000.0,True,1.0,False,False,False,One,Conejo,2.0,20500.0,...,1134739945,1140.0,SingleFamilyResidence,2026-01-31,SR25218548,CA,2025-09-16,34.655489,-118.205478,3.0
10231,840000.0,True,2.0,True,False,False,Two,RanchoSoutheast,2.0,5107.0,...,1144635049,2791.0,SingleFamilyResidence,2026-01-31,WS25246759,CA,2025-10-07,34.009959,-117.593657,5.0
2,2975000.0,True,1.0,NaN,False,False,One,NaN,0.0,238186.0,...,1151959385,1600.0,SingleFamilyResidence,2026-01-31,41122676,CA,2026-01-31,37.878010,-121.868460,2.0
12271,770000.0,False,1.0,False,False,False,One,Arcadia,2.0,6104.0,...,1137316585,1603.0,SingleFamilyResidence,2026-01-31,DW25228486,CA,2025-09-29,33.942085,-118.043587,3.0
1627,1350000.0,True,1.0,NaN,False,False,One,Mlslistings,2.0,6760.0,...,1150114839,1269.0,SingleFamilyResidence,2026-01-30,41119886,CA,2026-01-02,37.541337,-121.978632,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14741,350000.0,False,NaN,False,NaN,False,NaN,Mlslistings,2.0,6098.0,...,1120193042,1119.0,SingleFamilyResidence,2026-01-01,ML82016477,CA,2025-07-31,38.480602,-121.500243,3.0
12781,810000.0,NaN,1.0,False,False,False,One,Southland,2.0,5021.0,...,1136724065,1747.0,SingleFamilyResidence,2026-01-01,DW25222646,CA,2025-09-11,34.220024,-118.394489,3.0
15480,410000.0,NaN,1.0,True,True,False,One,SierraNorthValley,0.0,20473.0,...,1118267281,1352.0,SingleFamilyResidence,2026-01-01,SN25137783,CA,2025-06-19,39.799295,-121.895948,4.0
15617,710000.0,True,1.0,True,False,False,One,NorthSanLuisObispo,2.0,87120.0,...,1115109409,1873.0,SingleFamilyResidence,2026-01-01,PI25128639,CA,2025-05-28,35.634321,-120.547108,4.0
8304,750000.0,True,1.0,False,False,False,One,Downey,2.0,6476.0,...,1146029275,954.0,SingleFamilyResidence,2026-01-01,OC25257147,CA,2025-11-09,34.117327,-117.896108,3.0

In [7]:
df_train_dec.isna().sum()

ClosePrice                     0
AttachedGarageYN            8163
Stories                     7001
ViewYN                      6506
PoolPrivateYN               5268
NewConstructionYN           5151
Levels                      4712
BuyerOfficeAOR              4074
GarageSpaces                2745
LotSizeSquareFeet           1153
LotSizeAcres                1151
LotSizeArea                 1143
BuyerOfficeName              783
ListAgentFirstName           490
BuyerAgentFirstName          297
ListAgentEmail               233
BuyerAgentMlsId               71
StreetNumberNumeric           62
UnparsedAddress               48
FireplaceYN                   47
YearBuilt                     35
BuyerAgentLastName            28
City                          23
ListAgentFullName             19
BuyerAgentAOR                 11
BathroomsTotalInteger         11
ListAgentAOR                  11
ListAgentLastName              8
PostalCode                     1
ParkingTotal                   1
PropertyType                   0
ListingKeyNumeric              0
ListOfficeName                 0
CountyOrParish                 0
MlsStatus                      0
DaysOnMarket                   0
ListingKey                     0
LivingArea                     0
PropertySubType                0
ContractStatusChangeDate       0
ListingId                      0
StateOrProvince                0
ListingContractDate            0
Latitude                       0
Longitude                      0
BedroomsTotal                  0
dtype: int64

In [8]:
columns_to_impute = [
    "AttachedGarageYN",
    "Stories",
    "ViewYN",
    "PoolPrivateYN",
    "NewConstructionYN",
    "Levels",
    "BuyerOfficeAOR",
    "GarageSpaces",
    "LotSizeSquareFeet",
    "LotSizeAcres",
    "LotSizeArea",
    "BuyerOfficeName",
    "ListAgentFirstName",
    "BuyerAgentFirstName",
    "ListAgentEmail",
    "BuyerAgentMlsId",
    "StreetNumberNumeric",
    "UnparsedAddress",
    "FireplaceYN",
    "YearBuilt",
    "BuyerAgentLastName",
    "City",
    "ListAgentFullName",
    "BuyerAgentAOR",
    "BathroomsTotalInteger",
    "ListAgentAOR",
    "ListAgentLastName",
    "PostalCode",
    "ParkingTotal"
]




def random_sample_impute(train_df, test_df, column):
    observed_values = train_df[column].dropna().values
    
    
    train_missing = train_df[column].isna()
    train_df.loc[train_missing, column] = np.random.choice(
        observed_values,
        size=train_missing.sum(),
        replace=True
    )
    
    #
    test_missing = test_df[column].isna()
    test_df.loc[test_missing, column] = np.random.choice(
        observed_values,
        size=test_missing.sum(),
        replace=True
    )
    
    return train_df, test_df

for col in columns_to_impute:
    df_train_dec, df_test_dec = random_sample_impute(
        df_train_dec,
        df_test_dec,
        col
    )
df_train_dec
df_train_dec.isna().sum().sum()
df_test_dec.isna().sum().sum()

np.int64(0)

In [9]:
df_train_jan.isna().sum()

ClosePrice                     0
AttachedGarageYN            8141
Stories                     6689
ViewYN                      6242
PoolPrivateYN               5057
NewConstructionYN           5029
Levels                      4437
BuyerOfficeAOR              4628
GarageSpaces                2671
LotSizeSquareFeet           1113
LotSizeAcres                1112
LotSizeArea                 1106
BuyerOfficeName              734
ListAgentFirstName           470
BuyerAgentFirstName          276
ListAgentEmail               233
BuyerAgentMlsId               82
StreetNumberNumeric           66
UnparsedAddress               48
FireplaceYN                   48
YearBuilt                     32
BuyerAgentLastName            34
City                          13
ListAgentFullName             23
BuyerAgentAOR                 11
BathroomsTotalInteger          7
ListAgentAOR                  11
ListAgentLastName              7
PostalCode                     1
ParkingTotal                   0
PropertyType                   0
ListingKeyNumeric              0
ListOfficeName                 0
CountyOrParish                 0
MlsStatus                      0
DaysOnMarket                   0
ListingKey                     0
LivingArea                     0
PropertySubType                0
ContractStatusChangeDate       0
ListingId                      0
StateOrProvince                0
ListingContractDate            0
Latitude                       0
Longitude                      0
BedroomsTotal                  0
dtype: int64

In [10]:
columns_jan = [
    "AttachedGarageYN",
    "Stories",
    "ViewYN",
    "PoolPrivateYN",
    "NewConstructionYN",
    "Levels",
    "BuyerOfficeAOR",
    "GarageSpaces",
    "LotSizeSquareFeet",
    "LotSizeAcres",
    "LotSizeArea",
    "BuyerOfficeName",
    "ListAgentFirstName",
    "BuyerAgentFirstName",
    "ListAgentEmail",
    "BuyerAgentMlsId",
    "StreetNumberNumeric",
    "UnparsedAddress",
    "FireplaceYN",
    "YearBuilt",
    "BuyerAgentLastName",
    "City",
    "ListAgentFullName",
    "BuyerAgentAOR",
    "BathroomsTotalInteger",
    "ListAgentAOR",
    "ListAgentLastName",
    "PostalCode"
]

for col in columns_jan:
    df_train_jan, df_test_jan = random_sample_impute(
        df_train_jan,
        df_test_jan,
        col
    )

In [11]:
df_train_jan.columns

Index(['ClosePrice', 'AttachedGarageYN', 'Stories', 'ViewYN', 'PoolPrivateYN',
       'NewConstructionYN', 'Levels', 'BuyerOfficeAOR', 'GarageSpaces',
       'LotSizeSquareFeet', 'LotSizeAcres', 'LotSizeArea', 'BuyerOfficeName',
       'ListAgentFirstName', 'BuyerAgentFirstName', 'ListAgentEmail',
       'BuyerAgentMlsId', 'StreetNumberNumeric', 'UnparsedAddress',
       'FireplaceYN', 'YearBuilt', 'BuyerAgentLastName', 'City',
       'ListAgentFullName', 'BuyerAgentAOR', 'BathroomsTotalInteger',
       'ListAgentAOR', 'ListAgentLastName', 'PostalCode', 'ParkingTotal',
       'PropertyType', 'ListingKeyNumeric', 'ListOfficeName', 'CountyOrParish',
       'MlsStatus', 'DaysOnMarket', 'ListingKey', 'LivingArea',
       'PropertySubType', 'ContractStatusChangeDate', 'ListingId',
       'StateOrProvince', 'ListingContractDate', 'Latitude', 'Longitude',
       'BedroomsTotal'],
      dtype='object')

Removed BuyerOfficeAOR, BuyerOfficeName, ListAgentFirstName, BuyerAgentFirstName, ListAgentEmail, BuyerAgentMlsId, StreetNumberNumeric, UnparsedAddress, BuyerAgentLastName, ListAgentFullName, BuyerAgentAOR, ListAgentAOR, ListingKeyNumeric, ListingKey, ListingId, ListAgentLastName, ListOfficeName, ContractStatusChangeDate, and ListingContractDate because they do not seem to have any importance with the close price.

In [ ]:
import statsmodels.formula.api as smf
from sklearn.metrics import r2_score

predictors_clean = [
    "AttachedGarageYN",
    "Stories",
    "ViewYN",
    "PoolPrivateYN",
    "NewConstructionYN",
    "Levels",
    "GarageSpaces",
    "LotSizeSquareFeet",
    "LotSizeAcres",
    "LotSizeArea",
    "FireplaceYN",
    "YearBuilt",
    "City",
    "BathroomsTotalInteger",
    "PostalCode",
    "ParkingTotal",
    "PropertyType",
    "CountyOrParish",
    "MlsStatus",
    "DaysOnMarket",
    "LivingArea",
    "PropertySubType",
    "StateOrProvince",
    "Latitude",
    "Longitude",
    "BedroomsTotal"
]

categorical_columns = [
    col for col in predictors_clean
    if df_train_dec[col].dtype == "object"
]

for col in categorical_columns:
    # work with plain objects/strings first
    df_train_dec[col] = df_train_dec[col].astype("object")
    df_test_dec[col]  = df_test_dec[col].astype("object")

    # categories seen in training
    train_cats = set(df_train_dec[col].dropna().unique())

    # map unseen test categories -> "Other"
    df_test_dec.loc[~df_test_dec[col].isin(train_cats) & df_test_dec[col].notna(), col] = "Other"

    # ensure "Other" exists in training (so it becomes a valid category)
    if "Other" not in train_cats:
        df_train_dec.loc[df_train_dec[col].isna(), col] = "Other"  # minimal way to introduce it

    # now convert to category and align
    df_train_dec[col] = df_train_dec[col].astype("category")
    df_test_dec[col]  = df_test_dec[col].astype("category").cat.set_categories(df_train_dec[col].cat.categories)
formula = "ClosePrice ~ " + " + ".join([f'C({c})' if c in categorical_columns else c for c in predictors_clean])

model = smf.ols(formula=formula, data=df_train_dec).fit()

print(model.summary())



actual = df_test_dec["ClosePrice"]
pred_vals = model.predict(df_test_dec)

# actual = df_test_cleaned["ClosePrice"]

mask = actual.notna() & pd.Series(pred_vals).notna()
r_squared_lin = r2_score(actual[mask], pd.Series(pred_vals)[mask])


mape_lin = mape(actual[mask], pd.Series(pred_vals)[mask])
print("Rsquared linear: ", r_squared_lin)
print("MaPe linear: ", mape_lin)

                            OLS Regression Results
==============================================================================
Dep. Variable:             ClosePrice   R-squared:                       0.169
Model:                            OLS   Adj. R-squared:                  0.144
Method:                 Least Squares   F-statistic:                     6.760
Date:                Sat, 28 Feb 2026   Prob (F-statistic):               0.00
Time:                        00:42:03   Log-Likelihood:            -1.1843e+06
No. Observations:               68286   AIC:                         2.373e+06
Df Residuals:                   66285   BIC:                         2.391e+06
Df Model:                        2000
Covariance Type:            nonrobust
========================================================================================================
                                           coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                            -2.079e+08   1.04e+08     -2.002      0.045   -4.12e+08   -4.31e+06
AttachedGarageYN[T.True]             -2.244e+05      1e+05     -2.233      0.026   -4.21e+05   -2.74e+04
ViewYN[T.True]                        4.822e+04   7.31e+04      0.659      0.510   -9.51e+04    1.92e+05
PoolPrivateYN[T.True]                 3.606e+04   9.77e+04      0.369      0.712   -1.55e+05    2.28e+05
NewConstructionYN[T.True]             9.374e+04   1.99e+05      0.471      0.638   -2.97e+05    4.84e+05
Levels[T.MultiSplit,One]              2.401e+05   1.66e+06      0.145      0.885   -3.02e+06     3.5e+06
Levels[T.One]                         1.757e+05   2.86e+05      0.615      0.538   -3.84e+05    7.35e+05
Levels[T.One,MultiSplit]             -2.017e+05   1.49e+06     -0.135      0.893   -3.13e+06    2.72e+06
Levels[T.One,ThreeOrMore]            -3.826e+04   2.99e+06     -0.013      0.990   -5.91e+06    5.83e+06
Levels[T.One,Two]                    -1.274e+05    7.2e+05     -0.177      0.860   -1.54e+06    1.28e+06
Levels[T.One,Two,MultiSplit]         -3.417e+05   5.98e+06     -0.057      0.954   -1.21e+07    1.14e+07
Levels[T.One,Two,ThreeOrMore]        -2.584e+06   8.41e+06     -0.307      0.759   -1.91e+07    1.39e+07
Levels[T.ThreeOrMore]                 5.002e+04   3.61e+05      0.139      0.890   -6.57e+05    7.57e+05
Levels[T.ThreeOrMore,MultiSplit]      7.715e+05   1.38e+06      0.559      0.576   -1.93e+06    3.48e+06
Levels[T.ThreeOrMore,One]             9.099e+05   4.87e+06      0.187      0.852   -8.64e+06    1.05e+07
Levels[T.Two]                         2.608e+04   2.98e+05      0.088      0.930   -5.57e+05    6.09e+05
Levels[T.Two,MultiSplit]             -1.178e+04   8.59e+05     -0.014      0.989    -1.7e+06    1.67e+06
Levels[T.Two,One]                    -2.703e+04   6.32e+05     -0.043      0.966   -1.27e+06    1.21e+06
Levels[T.Two,ThreeOrMore]             2.525e+05   1.92e+06      0.131      0.896   -3.52e+06    4.02e+06
Levels[T.Two,ThreeOrMore,MultiSplit] -2.346e+05   5.99e+06     -0.039      0.969    -1.2e+07    1.15e+07
FireplaceYN[T.True]                  -1.883e+05    8.4e+04     -2.242      0.025   -3.53e+05   -2.37e+04
City[T.Acton]                        -2.929e+05   1.25e+06     -0.234      0.815   -2.75e+06    2.16e+06
City[T.Adelanto]                      9.738e+05   2.99e+06      0.326      0.745   -4.88e+06    6.83e+06
City[T.Agoura]                       -7.988e+05   7.87e+06     -0.102      0.919   -1.62e+07    1.46e+07
City[T.Agoura Hills]                 -1.379e+06   2.32e+06     -0.595      0.552   -5.92e+06    3.16e+06
City[T.Agua Dulce]                    2.055e+06   2.93e+06      0.701      0.483   -3.69e+06     7.8e+06
City[T.Aguanga]                       4.153e+05   2.03e+06      0.205      0.838   -3.56e+06    4.39e+06
City[T.Ahwahnee]                      4.465e+05   3.78e+06      0.118      0.906   -6.96e+06    7.85e+06
City[T.Alameda]                       -2.62e+06    4.1e+06     -0.639      0.523   -1.07e+07    5.42e+06
City[T.Alamo]                         -1.21e+06   4.52e+06     -0.267      0.789   -1.01e+07    7.65e+06
City[T.Albany]                       -2.505e+06   6.33e+06     -0.396      0.692   -1.49e+07     9.9e+06
City[T.Alhambra]                     -6.267e+05   1.48e+06     -0.424      0.671   -3.52e+06    2.27e+06
City[T.Aliso Viejo]                  -2.543e+05   4.83e+06     -0.053      0.958   -9.72e+06    9.21e+06
City[T.Alpine]                       -5.896e+05   2.77e+06     -0.212      0.832   -6.03e+06    4.85e+06
City[T.Alta Loma]                     3.639e+05   2.47e+06      0.147      0.883   -4.47e+06     5.2e+06
City[T.Altadena]                     -3.052e+05   1.09e+06     -0.281      0.779   -2.43e+06    1.82e+06
City[T.Alviso]                        -2.15e+05   1.24e+07     -0.017      0.986   -2.44e+07     2.4e+07
City[T.American Canyon]              -4.884e+05   2.04e+06     -0.239      0.811   -4.49e+06    3.51e+06
City[T.Anaheim]                      -6.022e+05   5.79e+06     -0.104      0.917   -1.19e+07    1.07e+07
City[T.Anaheim Hills]                -5.273e+05   5.86e+06     -0.090      0.928    -1.2e+07     1.1e+07
City[T.Anderson]                      4.737e+05   3.26e+06      0.145      0.885   -5.93e+06    6.87e+06
City[T.Angelus Oaks]                  9.032e+05   2.01e+06      0.448      0.654   -3.04e+06    4.85e+06
City[T.Antelope]                      2.933e+05   1.55e+06      0.189      0.850   -2.75e+06    3.34e+06
City[T.Antioch]                       2.417e+05    8.4e+06      0.029      0.977   -1.62e+07    1.67e+07
City[T.Anza]                          6.203e+05   2.07e+06      0.299      0.765   -3.44e+06    4.68e+06
City[T.Apple Valley]                  9.144e+05   4.28e+06      0.214      0.831   -7.47e+06     9.3e+06
City[T.Aptos]                        -2.375e+05   3.12e+06     -0.076      0.939   -6.36e+06    5.88e+06
City[T.Arcadia]                      -3.475e+05   3.62e+06     -0.096      0.923   -7.44e+06    6.74e+06
City[T.Arleta]                       -2.069e+05    7.2e+06     -0.029      0.977   -1.43e+07    1.39e+07
City[T.Arnold]                        7.144e+05   1.99e+06      0.359      0.720   -3.19e+06    4.62e+06
City[T.Aromas]                       -1.842e+06   8.58e+06     -0.215      0.830   -1.86e+07     1.5e+07
City[T.Arrowbear]                      1.26e+06   5.24e+06      0.241      0.810   -9.01e+06    1.15e+07
City[T.Arroyo Grande]                -8.614e+05   5.49e+06     -0.157      0.875   -1.16e+07     9.9e+06
City[T.Artesia]                      -6.218e+05   6.28e+06     -0.099      0.921   -1.29e+07    1.17e+07
City[T.Artois]                        2.574e+05   2.66e+06      0.097      0.923   -4.95e+06    5.46e+06
City[T.Arvin]                        -8.061e+06   4.51e+06     -1.786      0.074   -1.69e+07    7.87e+05
City[T.Atascadero]                   -4.526e+05   1.86e+06     -0.243      0.808    -4.1e+06     3.2e+06
City[T.Atherton]                      2.501e+06   4.44e+06      0.564      0.573    -6.2e+06    1.12e+07
City[T.Atwater]                       9.958e+04   7.63e+05      0.131      0.896    -1.4e+06    1.59e+06
City[T.Atwater Village]              -3.534e+05   9.29e+06     -0.038      0.970   -1.86e+07    1.79e+07
City[T.Auberry]                       8.945e+05    2.4e+06      0.373      0.709    -3.8e+06    5.59e+06
City[T.Auburn]                       -3.773e+06   9.81e+06     -0.385      0.701    -2.3e+07    1.55e+07
City[T.Avalon]                       -1.353e+06   3.18e+06     -0.426      0.670   -7.58e+06    4.88e+06
City[T.Avila Beach]                  -4.579e+05   2.32e+06     -0.198      0.843      -5e+06    4.09e+06
City[T.Azusa]                        -1.259e+05   1.08e+06     -0.116      0.907   -2.25e+06    1.99e+06
City[T.Bakersfield]                  -1.332e+07   3.53e+06     -3.770      0.000   -2.02e+07   -6.39e+06
City[T.Baldwin Park]                 -2.979e+05   2.19e+06     -0.136      0.892   -4.58e+06    3.99e+06
City[T.Ballico]                       8.678e+04   3.94e+06      0.022      0.982   -7.64e+06    7.82e+06
City[T.Bangor]                        2.339e+05   2.35e+06      0.099      0.921   -4.38e+06    4.85e+06
City[T.Banning]                       9.439e+05   1.79e+06      0.526      0.599   -2.57e+06    4.46e+06
City[T.Barstow]                       1.725e+06   1.56e+06      1.106      0.269   -1.33e+06    4.78e+06
City[T.Bass Lake]                     1.019e+06   4.14e+06      0.246      0.806    -7.1e+06    9.14e+06
City[T.Bay Point]                    -1.771e+06    3.6e+06     -0.491      0.623   -8.83e+06    5.29e+06
City[T.Beaumont]                      7.529e+05   4.67e+06      0.161      0.872   -8.41e+06    9.91e+06
City[T.Bel Air]                      -2.007e+06   7.21e+06     -0.278      0.781   -1.61e+07    1.21e+07
City[T.Bell]                         -5.984e+05    3.2e+06     -0.187      0.852   -6.88e+06    5.68e+06
City[T.Bell Canyon]                  -1.775e+06   3.21e+06     -0.553      0.580   -8.07e+06    4.52e+06
City[T.Bell Gardens]                 -8.111e+04   4.77e+06     -0.017      0.986   -9.43e+06    9.27e+06
City[T.Bellflower]                   -4.552e+05   1.23e+07     -0.037      0.970   -2.45e+07    2.36e+07
City[T.Belmont]                      -2.019e+05   7.23e+05     -0.279      0.780   -1.62e+06    1.21e+06
City[T.Ben Lomond]                   -8.305e+05   2.19e+06     -0.379      0.704   -5.12e+06    3.46e+06
City[T.Benicia]                      -5.646e+05    1.2e+06     -0.470      0.639   -2.92e+06    1.79e+06
City[T.Berkeley]                     -2.337e+06   3.85e+06     -0.608      0.543   -9.87e+06     5.2e+06
City[T.Bermuda Dunes]                 1.228e+06   2.16e+06      0.568      0.570   -3.01e+06    5.46e+06
City[T.Berry Creek]                   5.772e+05   2.86e+06      0.202      0.840   -5.02e+06    6.17e+06
City[T.Bethel Island]                -8.043e+05   1.96e+06     -0.411      0.681   -4.64e+06    3.03e+06
City[T.Beverly Hills]                 3.203e+06    9.2e+06      0.348      0.728   -1.48e+07    2.12e+07
City[T.Big Bar]                      -3.246e+05   3.81e+06     -0.085      0.932    -7.8e+06    7.15e+06
City[T.Big Bear]                      1.045e+06   3.37e+06      0.310      0.757   -5.56e+06    7.65e+06
City[T.Big Bear City]                 1.033e+06   3.43e+06      0.301      0.763   -5.69e+06    7.75e+06
City[T.Big Bear Lake]                  9.73e+05    3.6e+06      0.270      0.787   -6.08e+06    8.03e+06
City[T.Big River]                     4.133e+06   3.29e+06      1.257      0.209   -2.31e+06    1.06e+07
City[T.Big Sur]                      -3.108e+05   2.81e+06     -0.111      0.912   -5.82e+06     5.2e+06
City[T.Biggs]                         -1.16e+05   2.06e+06     -0.056      0.955   -4.16e+06    3.93e+06
City[T.Bishop]                        1.721e+06   2.43e+06      0.708      0.479   -3.05e+06    6.49e+06
City[T.Bloomington]                    4.11e+05   1.43e+06      0.286      0.775    -2.4e+06    3.22e+06
City[T.Blue Jay]                      1.519e+06    5.2e+06      0.292      0.770   -8.68e+06    1.17e+07
City[T.Blythe]                        3.442e+06   2.41e+06      1.429      0.153   -1.28e+06    8.16e+06
City[T.Bombay Beach]                  9.995e+05   4.97e+06      0.201      0.841   -8.74e+06    1.07e+07
City[T.Bonita]                       -1.671e+06   1.17e+07     -0.142      0.887   -2.47e+07    2.13e+07
City[T.Bonsall]                       3.579e+04   2.83e+06      0.013      0.990   -5.51e+06    5.58e+06
City[T.Boron]                        -6.885e+06   2.86e+06     -2.405      0.016   -1.25e+07   -1.27e+06
City[T.Borrego Springs]               1.743e+05   2.91e+06      0.060      0.952   -5.53e+06    5.88e+06
City[T.Boulder Creek]                -8.467e+05   1.97e+06     -0.430      0.667   -4.71e+06    3.01e+06
City[T.Boulevard]                     -2.27e+05   3.16e+06     -0.072      0.943   -6.42e+06    5.96e+06
City[T.Bradbury]                     -9122.5228   4.91e+06     -0.002      0.999   -9.64e+06    9.62e+06
City[T.Bradley]                       -5.41e+05   1.87e+06     -0.289      0.772   -4.21e+06    3.12e+06
City[T.Brawley]                       1.194e+06   3.62e+06      0.330      0.742    -5.9e+06    8.29e+06
City[T.Brea]                         -2.094e+06   1.39e+07     -0.151      0.880   -2.93e+07    2.51e+07
City[T.Brentwood]                    -2.021e+06   3.52e+06     -0.573      0.566   -8.93e+06    4.89e+06
City[T.Brisbane]                     -5.947e+05   1.41e+06     -0.423      0.673   -3.35e+06    2.16e+06
City[T.Brookdale]                     -9.79e+05   4.49e+06     -0.218      0.827   -9.78e+06    7.82e+06
City[T.Browns Valley]                 3.926e+05   2.83e+06      0.139      0.890   -5.16e+06    5.94e+06
City[T.Brownsville]                  -6.129e+04   3.89e+06     -0.016      0.987   -7.69e+06    7.57e+06
City[T.Bucks Lake]                     3.87e+05   5.83e+06      0.066      0.947    -1.1e+07    1.18e+07
City[T.Buellton]                     -1.016e+07   3.72e+06     -2.734      0.006   -1.75e+07   -2.88e+06
City[T.Buena Park]                   -5.265e+05   6.85e+06     -0.077      0.939   -1.39e+07    1.29e+07
City[T.Burbank]                       1.198e+05   7.45e+06      0.016      0.987   -1.45e+07    1.47e+07
City[T.Burlingame]                   -6.114e+05   1.04e+06     -0.586      0.558   -2.66e+06    1.43e+06
City[T.Butte Meadows]                 9.017e+05    5.6e+06      0.161      0.872   -1.01e+07    1.19e+07
City[T.Butte Valley]                  9.811e+04   3.59e+06      0.027      0.978   -6.94e+06    7.13e+06
City[T.Buttonwillow]                 -8.934e+06   4.51e+06     -1.982      0.047   -1.78e+07   -9.88e+04
City[T.Byron]                        -1.874e+06   5.48e+06     -0.342      0.732   -1.26e+07    8.87e+06
City[T.Cabazon]                       1.202e+06   2.59e+06      0.465      0.642   -3.87e+06    6.27e+06
City[T.Calabasas]                    -1.117e+06   2.19e+06     -0.511      0.609    -5.4e+06    3.17e+06
City[T.Calexico]                      9.659e+05   3.29e+06      0.294      0.769   -5.47e+06     7.4e+06
City[T.California City]              -2.606e+06   7.95e+06     -0.328      0.743   -1.82e+07     1.3e+07
City[T.Calimesa]                      8.571e+05   1.85e+06      0.464      0.643   -2.77e+06    4.48e+06
City[T.Calistoga]                    -4.116e+05   3.84e+06     -0.107      0.915   -7.94e+06    7.12e+06
City[T.Camarillo]                    -5.657e+05   3.66e+06     -0.154      0.877   -7.75e+06    6.61e+06
City[T.Cambria]                          -7e+05   1.91e+06     -0.366      0.715   -4.45e+06    3.05e+06
City[T.Cameron Park]                 -1.806e+05   2.84e+06     -0.064      0.949   -5.75e+06    5.39e+06
City[T.Campbell]                       1.09e+05   1.66e+06      0.066      0.948   -3.14e+06    3.36e+06
City[T.Campo]                        -4.643e+05   2.93e+06     -0.159      0.874    -6.2e+06    5.27e+06
City[T.Canoga Park]                  -7.139e+05   1.93e+06     -0.371      0.711   -4.49e+06    3.06e+06
City[T.Canyon Country]               -1.481e+06   2.76e+06     -0.537      0.591   -6.88e+06    3.92e+06
City[T.Canyon Lake]                   3.038e+05   3.03e+06      0.100      0.920   -5.63e+06    6.24e+06
City[T.Capitola]                     -3.144e+05   1.98e+06     -0.159      0.874   -4.19e+06    3.56e+06
City[T.Cardiff By The Sea]           -1.067e+06   1.18e+07     -0.091      0.928   -2.42e+07     2.2e+07
City[T.Carlsbad]                      -1.66e+06   1.17e+07     -0.142      0.887   -2.45e+07    2.12e+07
City[T.Carmel]                       -3.827e+05   1.01e+07     -0.038      0.970   -2.01e+07    1.94e+07
City[T.Carmel Valley]                -1.162e+06   8.82e+06     -0.132      0.895   -1.85e+07    1.61e+07
City[T.Carmichael]                    1.934e+05   3.03e+06      0.064      0.949   -5.74e+06    6.13e+06
City[T.Carpinteria]                  -8.909e+06   3.69e+06     -2.417      0.016   -1.61e+07   -1.68e+06
City[T.Carson]                       -1.077e+06   4.22e+06     -0.255      0.798   -9.35e+06    7.19e+06
City[T.Caruthers]                    -5.364e+05   4.03e+06     -0.133      0.894   -8.43e+06    7.35e+06
City[T.Castaic]                      -7.181e+05    1.1e+06     -0.653      0.514   -2.87e+06    1.44e+06
City[T.Castro Valley]                -3.002e+06   5.15e+06     -0.583      0.560   -1.31e+07     7.1e+06
City[T.Castroville]                  -3.475e+05    2.8e+06     -0.124      0.901   -5.84e+06    5.15e+06
City[T.Cathedral City]                1.433e+06   1.86e+06      0.772      0.440    -2.2e+06    5.07e+06
City[T.Catheys Valley]               -2.893e+05   3.56e+06     -0.081      0.935   -7.27e+06    6.69e+06
City[T.Cayucos]                      -3.173e+05   2.19e+06     -0.145      0.885   -4.61e+06    3.98e+06
City[T.Cedar Glen]                    8.546e+05   6.19e+06      0.138      0.890   -1.13e+07     1.3e+07
City[T.Cedarpines Park]               7.411e+05   1.79e+06      0.414      0.679   -2.77e+06    4.25e+06
City[T.Ceres]                        -2.315e+05   9.08e+06     -0.025      0.980    -1.8e+07    1.76e+07
City[T.Cerritos]                     -2.507e+05   4.25e+06     -0.059      0.953   -8.57e+06    8.07e+06
City[T.Challenge]                     4.978e+05   2.85e+06      0.175      0.861   -5.08e+06    6.07e+06
City[T.Chatsworth]                       -1e+06    1.1e+06     -0.906      0.365   -3.16e+06    1.16e+06
City[T.Cherry Valley]                  8.38e+05   4.57e+06      0.183      0.855   -8.12e+06     9.8e+06
City[T.Chester]                       4.505e+05   4.22e+06      0.107      0.915   -7.82e+06    8.72e+06
City[T.Chico]                          1.62e+05   2.17e+06      0.075      0.941    -4.1e+06    4.42e+06
City[T.Chino]                        -3.661e+05    1.4e+07     -0.026      0.979   -2.78e+07    2.71e+07
City[T.Chino Hills]                  -2.226e+05   2.71e+06     -0.082      0.935   -5.54e+06     5.1e+06
City[T.Chowchilla]                   -4.198e+05      4e+06     -0.105      0.916   -8.26e+06    7.42e+06
City[T.Chualar]                       -2.85e+05    2.8e+06     -0.102      0.919   -5.76e+06    5.19e+06
City[T.Chula Vista]                  -1.639e+06   4.58e+06     -0.358      0.720   -1.06e+07    7.33e+06
City[T.Citrus Heights]                2.957e+05   2.88e+06      0.103      0.918   -5.35e+06    5.94e+06
City[T.City Terrace]                 -8.619e+04   5.41e+06     -0.016      0.987   -1.07e+07    1.05e+07
City[T.Clairemont Mesa]              -6.833e+06   1.01e+07     -0.674      0.500   -2.67e+07     1.3e+07
City[T.Claremont]                     1.431e+04   1.05e+06      0.014      0.989   -2.04e+06    2.07e+06
City[T.Clayton]                      -1.515e+06   3.59e+06     -0.422      0.673   -8.55e+06    5.52e+06
City[T.Clearlake]                     1.946e+05   4.86e+06      0.040      0.968   -9.32e+06    9.71e+06
City[T.Clearlake Oaks]                1.048e+05   1.08e+06      0.097      0.923   -2.01e+06    2.22e+06
City[T.Clearlake Park]               -4.443e+04   7.38e+06     -0.006      0.995   -1.45e+07    1.44e+07
City[T.Cloverdale]                   -3.663e+05   4.06e+06     -0.090      0.928   -8.32e+06    7.59e+06
City[T.Clovis]                        3.048e+05   1.32e+06      0.230      0.818   -2.29e+06     2.9e+06
City[T.Coachella]                      2.02e+06   3.76e+06      0.538      0.591   -5.34e+06    9.38e+06
City[T.Coalinga]                     -1.494e+06   1.46e+06     -1.027      0.305   -4.35e+06    1.36e+06
City[T.Coarsegold]                    2.383e+05   3.99e+06      0.060      0.952   -7.59e+06    8.06e+06
City[T.Cobb]                         -1.629e+05   3.58e+06     -0.046      0.964   -7.18e+06    6.85e+06

Empty DataFrame
Columns: [ClosePrice, AttachedGarageYN, Stories, ViewYN, PoolPrivateYN, NewConstructionYN, Levels, BuyerOfficeAOR, GarageSpaces, LotSizeSquareFeet, LotSizeAcres, LotSizeArea, BuyerOfficeName, ListAgentFirstName, BuyerAgentFirstName, ListAgentEmail, BuyerAgentMlsId, StreetNumberNumeric, UnparsedAddress, FireplaceYN, YearBuilt, BuyerAgentLastName, City, ListAgentFullName, BuyerAgentAOR, BathroomsTotalInteger, ListAgentAOR, ListAgentLastName, PostalCode, ParkingTotal, PropertyType, ListingKeyNumeric, ListOfficeName, CountyOrParish, MlsStatus, DaysOnMarket, ListingKey, LivingArea, PropertySubType, ContractStatusChangeDate, ListingId, StateOrProvince, ListingContractDate, Latitude, Longitude, BedroomsTotal]
Index: []

[0 rows x 46 columns]

In [ ]:
r_squared

NameError: name 'r_squared' is not defined